#!/bin/bash

: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${MATCHERS_DIR:=$HOME/.config/gurl}"

main(){

  dir=${__o[matchers-dir]:-$MATCHERS_DIR}
  
  [[ -z $dir ]] && ERX "MATCHERS_DIR not specified"
  [[ -d $dir ]] || _createconf "$dir"

  [[ -z ${url:=$1} ]] && ERX no url for gurl

  printf '%s\n' "$@" > "$dir/.last"

  mapfile -t files < <(find "${dir}/" -name match)

  ((${#files[@]} > 0)) && trg=$(awk -v url="$url" '
    /^[^#]/ {
      if (match(url,gensub(/^.+:\s+/,"",1,$0))) {
        dir = gensub(/[^/]+$/,"",1,FILENAME)
        print gensub(/^([^:]+).+/,dir "\\1",1,$1)
        exit
      }
    }
  ' "${files[@]}")

  [[ -f ${trg:=$dir/default} ]] && {
    export PATH=${tdir:=${trg%/*}}:$dir/_lib:$PATH
    cd "$tdir" || exit 1
    :
  } || trg=${trg##*/}

  command -v "$trg" >/dev/null && exec "$trg" "$@"
  ERX "$trg is not executable"
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
