#!/bin/bash

[[ $1 =~ ((http[s]?://)?gist[.]github[.]com/[^/]+/[^/]+)(/raw.*)? ]] && {
  url=${BASH_REMATCH[1]}/raw

  tmpfile="$(mktemp)"

  startwget "${BASH_REMATCH[1]}/raw" "$tmpfile" > /dev/null 2>&1 &
  trap 'stopwget' INT EXIT

  sublaunch

  wait

  subl "$tmpfile"
} 
